# Generated by Django 6.1.1 on 2026-09-14 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('Modelador', 'Modelador'), ('Scripter', 'Scripter'), ('Vfx Maker', 'Vfx Maker'), ('Ui Maker', 'Ui Maker'), ('Manager', 'Manager'), ('SFX Maker', 'SFX Maker')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('Modelador', 'Modelador'), ('Scripter', 'Scripter'), ('Vfx Maker', 'Vfx Maker'), ('Ui Maker', 'Ui Maker'), ('Manager', 'Manager'), ('SFX Maker', 'SFX Maker')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída')], default='Pendente', max_length=20)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
