# Generated by Django 6.1.1 on 2026-09-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_person_password_person_photo_activity_authtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
