# Generated by Django 5.2.12 on 2026-09-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_projectsettings_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
