# Generated by Django 5.2.12 on 2026-09-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_completion_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(default='oklch(0.62 0.15 200)', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.CharField(max_length=40),
        ),
    ]
