# Generated by Django 5.2.12 on 2026-09-15 15:23, hand-edited to preserve data:
# adds the new `roles` M2M, migrates each person's old single `role` string
# into it, then drops the old field — instead of the auto-generated
# remove-then-add order, which would silently drop everyone's role.

from django.db import migrations, models


def migrate_role_to_roles(apps, schema_editor):
    Person = apps.get_model('tasks', 'Person')
    Role = apps.get_model('tasks', 'Role')
    for person in Person.objects.exclude(role=''):
        role = Role.objects.filter(name=person.role).first()
        if role:
            person.roles.add(role)


def migrate_roles_to_role(apps, schema_editor):
    Person = apps.get_model('tasks', 'Person')
    for person in Person.objects.all():
        first_role = person.roles.first()
        if first_role:
            person.role = first_role.name
            person.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='people', to='tasks.role'),
        ),
        migrations.RunPython(migrate_role_to_roles, migrate_roles_to_role),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
