# Generated by Django 5.2.12 on 2026-09-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_project_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event_type',
            field=models.CharField(choices=[('task_created', 'Tarefa criada'), ('task_completed', 'Tarefa concluída'), ('task_status', 'Status alterado'), ('task_assigned', 'Responsável alterado'), ('task_updated', 'Tarefa atualizada'), ('checklist', 'Checklist'), ('comment', 'Comentário'), ('overdue', 'Atraso'), ('attachment', 'Anexo'), ('team', 'Equipe'), ('settings', 'Configuração'), ('system', 'Sistema')], default='system', max_length=30),
        ),
    ]
