# Generated by Django 5.2.12 on 2026-09-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_overdue_notified_alter_activity_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='discord_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
