# Generated by Django 5.2.12 on 2026-09-16 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_person_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_soon_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='in_progress_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='pending_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
