# Generated by Django 5.2.12 on 2026-09-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_person_last_digest_sent_at_task_due_soon_notified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(blank=True, max_length=32)),
                ('direction', models.CharField(choices=[('outgoing', 'Enviada'), ('incoming', 'Recebida')], max_length=10)),
                ('source', models.CharField(choices=[('admin', 'Mensagem manual (admin)'), ('pending_reminder', 'Lembrete: parada em Pendente'), ('in_progress_reminder', 'Lembrete: presa em Em andamento'), ('due_soon_reminder', 'Lembrete: prazo chegando'), ('digest', 'Resumo periódico'), ('dm', 'DM recebida')], max_length=30)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_messages', to='tasks.person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_messages', to='tasks.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
