# Generated by Django 5.2.12 on 2026-09-24 16:21

import django.db.models.deletion
import tasks.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_project_last_unverified_discord_reminder_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Geral', max_length=80)),
                ('kind', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('link', 'Link'), ('file', 'Arquivo')], max_length=10)),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=tasks.storages.get_reference_storage, upload_to='references/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='tasks.person')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
