# Generated by Django 6.1.1 on 2026-09-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='source',
            field=models.CharField(choices=[('admin', 'Mensagem manual (admin)'), ('pending_reminder', 'Lembrete: parada em Pendente'), ('in_progress_reminder', 'Lembrete: presa em Em andamento'), ('due_soon_reminder', 'Lembrete: prazo chegando'), ('unblocked', 'Aviso: tarefa liberada'), ('digest', 'Resumo periódico'), ('dm', 'DM recebida')], max_length=30),
        ),
    ]
