# Generated by Django 6.1.1 on 2026-09-25 22:29

import django.db.models.deletion
import tasks.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_task_depends_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=tasks.storages.get_reference_storage, upload_to='discord/')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(default='file', max_length=10)),
                ('is_gif', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.discordmessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
