# Generated by Django 6.1.1 on 2026-09-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_discord_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('solo', 'Solo'), ('group', 'Em grupo')], default='solo', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='group_tasks', to='tasks.person'),
        ),
    ]
