# Generated by Django 6.1.1 on 2026-09-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_task_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_completions', to='tasks.person')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.subtask')),
            ],
            options={
                'unique_together': {('subtask', 'person')},
            },
        ),
    ]
