# Generated by Django 6.1.1 on 2026-09-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_subtask_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='participant_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='source',
            field=models.CharField(choices=[('admin', 'Mensagem manual (admin)'), ('pending_reminder', 'Lembrete: parada em Pendente'), ('in_progress_reminder', 'Lembrete: presa em Em andamento'), ('due_soon_reminder', 'Lembrete: prazo chegando'), ('unblocked', 'Aviso: tarefa liberada'), ('your_turn', 'Aviso: sua vez na tarefa'), ('digest', 'Resumo periódico'), ('dm', 'DM recebida')], max_length=30),
        ),
    ]
